
name: 'citibike'
version: '1.0.0'
config-version: 2

profile: 'citibike'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
docs-paths: ["docs"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  citibike:
    +tags: 
      - citibike
  
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table
    semantic:
      +materialized: table

